server:
  port: 9527
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/travel #192.168.99.105   192.168.99.25
    username: root
    password: root  #gb.2312   Password1!GB.2312
mybatis:
  mapper-locations:  classpath:com/dengtao/travel/mapper/*mapper.xml #扫描mapper文件
  type-aliases-package: com.dengtao.travel.bean #配置别名
logging:
  level:
    com.dengtao.travel.mapper: DEBUG

